<a href="https://colab.research.google.com/github/Muhammad-Azham-Oman/AI_Portfolio/blob/main/Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [4]:
from sklearn.model_selection import cross_val_score

In [5]:
cross_val_score(LogisticRegression(max_iter=1000), X, y , cv=3)

array([0.98, 0.96, 0.98])

In [6]:
cross_val_score(SVC(max_iter=1000), X, y , cv=3)

array([0.96, 0.98, 0.94])

In [7]:
cross_val_score(RandomForestClassifier(), X, y , cv=3)

array([0.98, 0.94, 0.98])