<a href="https://colab.research.google.com/github/Muhammad-Azham-Oman/AI_Portfolio/blob/main/Dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv('carprices.csv')

In [ ]:
data

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [ ]:
dummies = pd.get_dummies(data['Car Model']).astype(int)

In [ ]:
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [ ]:
merged = pd.concat([data,dummies],axis=1)

In [ ]:
merged

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [ ]:
data_dummies = merged.drop(['Car Model', 'BMW X5'], axis=1)

In [ ]:
data_dummies

Mileage  Sell Price($)  Age(yrs)  Audi A5  Mercedez Benz C class
0     69000          18000         6        0                      0
1     35000          34000         3        0                      0
2     57000          26100         5        0                      0
3     22500          40000         2        0                      0
4     46000          31500         4        0                      0
5     59000          29400         5        1                      0
6     52000          32000         5        1                      0
7     72000          19300         6        1                      0
8     91000          12000         8        1                      0
9     67000          22000         6        0                      1
10    83000          20000         7        0                      1
11    79000          21000         7        0                      1
12    59000          33000         5        0                      1

In [ ]:
X = data_dummies.drop(['Sell Price($)'],axis=1)

In [ ]:
y = data_dummies['Sell Price($)']

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
model.predict([[45000,4,0,1]])

array([36991.31721031])

In [ ]:
model.predict([[86000,7,0,0]])

array([11080.74313267])

In [ ]:
model.score(X,y)

0.9417050937281082

In [ ]:
# By one hot encoding

In [ ]:
le = LabelEncoder()

In [ ]:
dfle = data

In [ ]:
dfle['Car Model'] = le.fit_transform(dfle['Car Model'])

In [ ]:
dfle

Car Model  Mileage  Sell Price($)  Age(yrs)
0           1    69000          18000         6
1           1    35000          34000         3
2           1    57000          26100         5
3           1    22500          40000         2
4           1    46000          31500         4
5           0    59000          29400         5
6           0    52000          32000         5
7           0    72000          19300         6
8           0    91000          12000         8
9           2    67000          22000         6
10          2    83000          20000         7
11          2    79000          21000         7
12          2    59000          33000         5

In [ ]:
model_le = LinearRegression()

In [ ]:
X_le = dfle.drop(['Sell Price($)'],axis=1)
y_le = dfle['Sell Price($)']

In [ ]:
model_le.fit(X_le,y_le)

LinearRegression()

In [ ]:
model_le.predict([[2,45000,4]])

array([33336.7721827])

In [ ]:
model_le.predict([[1,86000,7]])

array([16106.74127344])

In [ ]:
model_le.score(X_le,y_le)

0.8719970367825953